//This file acts as a contract between the client and server,
// describing both the structure of the data and the remote procedure calls (RPCs)
// they use to communicate.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/chitchat.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int32                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ComponentName string                 `protobuf:"bytes,2,opt,name=componentName,proto3" json:"componentName,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=clientName,proto3" json:"clientName,omitempty"`
	HasJoined     bool                   `protobuf:"varint,5,opt,name=hasJoined,proto3" json:"hasJoined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageLog) Reset() {
	*x = MessageLog{}
	mi := &file_grpc_chitchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageLog) ProtoMessage() {}

func (x *MessageLog) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chitchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageLog.ProtoReflect.Descriptor instead.
func (*MessageLog) Descriptor() ([]byte, []int) {
	return file_grpc_chitchat_proto_rawDescGZIP(), []int{0}
}

func (x *MessageLog) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageLog) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *MessageLog) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MessageLog) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *MessageLog) GetHasJoined() bool {
	if x != nil {
		return x.HasJoined
	}
	return false
}

var File_grpc_chitchat_proto protoreflect.FileDescriptor

const file_grpc_chitchat_proto_rawDesc = "" +
	"\n" +
	"\x13grpc/chitchat.proto\x12\x04grpc\"\xac\x01\n" +
	"\n" +
	"MessageLog\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x05R\ttimestamp\x12$\n" +
	"\rcomponentName\x18\x02 \x01(\tR\rcomponentName\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x12\x1e\n" +
	"\n" +
	"clientName\x18\x04 \x01(\tR\n" +
	"clientName\x12\x1c\n" +
	"\thasJoined\x18\x05 \x01(\bR\thasJoined2C\n" +
	"\bChitChat\x127\n" +
	"\vSendMessage\x12\x10.grpc.MessageLog\x1a\x10.grpc.MessageLog\"\x00(\x010\x01B!Z\x1fdisys_chitchat_activity03/protob\x06proto3"

var (
	file_grpc_chitchat_proto_rawDescOnce sync.Once
	file_grpc_chitchat_proto_rawDescData []byte
)

func file_grpc_chitchat_proto_rawDescGZIP() []byte {
	file_grpc_chitchat_proto_rawDescOnce.Do(func() {
		file_grpc_chitchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_chitchat_proto_rawDesc), len(file_grpc_chitchat_proto_rawDesc)))
	})
	return file_grpc_chitchat_proto_rawDescData
}

var file_grpc_chitchat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpc_chitchat_proto_goTypes = []any{
	(*MessageLog)(nil), // 0: grpc.MessageLog
}
var file_grpc_chitchat_proto_depIdxs = []int32{
	0, // 0: grpc.ChitChat.SendMessage:input_type -> grpc.MessageLog
	0, // 1: grpc.ChitChat.SendMessage:output_type -> grpc.MessageLog
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_chitchat_proto_init() }
func file_grpc_chitchat_proto_init() {
	if File_grpc_chitchat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_chitchat_proto_rawDesc), len(file_grpc_chitchat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_chitchat_proto_goTypes,
		DependencyIndexes: file_grpc_chitchat_proto_depIdxs,
		MessageInfos:      file_grpc_chitchat_proto_msgTypes,
	}.Build()
	File_grpc_chitchat_proto = out.File
	file_grpc_chitchat_proto_goTypes = nil
	file_grpc_chitchat_proto_depIdxs = nil
}
