//This file acts as a contract between the client and server,
// describing both the structure of the data and the remote procedure calls (RPCs)
// they use to communicate.

syntax = "proto3";
package grpc;

option go_package = "disys_chitchat_activity03/proto";

//Our ChitChat Service. Contains only one rpc method, which receives and sends a stream of messages.
service RicartAgrawala {
  rpc Receive(Request) returns (Reply) {}
}

//Our message, containing necessary information.
message Request {
  int32 timestamp = 1;
  int32 sender_id = 2;
}

message Reply {
}